### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on JMETER 5.0

### ISSUE THREAD

**Issue by animavitis** [mariskamartin/jmeter-ajax-sampler#1]
Hi
I was trying to use your sampler but without luck. Everythings works fine when there is no headers, but when i try to add headers then it throws exception:

> 2019-01-31 11:26:54,687 DEBUG c.m.j.a.AjaxSampler: ARGS: {test=GET;;;https://google.com;;;xx;;;"xxx":"xxxx"}
2019-01-31 11:26:54,687 DEBUG c.m.j.a.AjaxSampler: Concurent thread pool size = 6
2019-01-31 11:26:54,688 INFO c.m.j.a.i.AjaxCall: Execute GET URL = https://google.com headers = "xxx":"xxxx" data = xx
2019-01-31 11:26:54,688 DEBUG c.m.j.a.i.AjaxCall: Start Executing GET request to URL: https://google.com (headers: "xxx":"xxxx") (data: xx)
2019-01-31 11:26:54,688 WARN c.m.j.a.i.AjaxCall: 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.mmariska.jmeter.ajax.impl.AjaxCall.execute(AjaxCall.java:55) [ajax-sampler-1.2.2-SNAPSHOT.jar:?]
	at com.mmariska.jmeter.ajax.impl.AjaxCall.call(AjaxCall.java:134) [ajax-sampler-1.2.2-SNAPSHOT.jar:?]
	at com.mmariska.jmeter.ajax.impl.AjaxCall.call(AjaxCall.java:18) [ajax-sampler-1.2.2-SNAPSHOT.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_192]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]

Can U tell me how can i add headers ??

**Comment by mariskamartin** [comment]
Hi I added example to repo. You need to use custom format for headers. 
use semicolon ';' as separator in third section. See
`POST;;;http://${server}/echo?param1=val1;;;some-string-POSTed-data:::Content-Type;application/json;header2;header2-value;header3;header3-value`

**Comment by animavitis** [comment]
Thank U
Works like a charm :)
